-- 1. Create the quotes table
create table quotes (
  id bigint generated by default as identity primary key,
  author text not null,
  quote text not null,
  source text,
  topic text,
  created_at timestamptz not null default now()
);

-- 2. Turn on Row Level Security
alter table quotes enable row level security;

-- 3. Allow anyone to read quotes (public site needs this)
create policy "Public read access"
  on quotes for select
  using (true);

-- No insert/update/delete policy is created for the public key on purpose.
-- Only the server-side admin endpoint (using the service_role key) will be
-- able to add new quotes -- the publishable key alone cannot write.
